[versions]
agp = "8.13.0"
desugar_jdk_libs = "2.1.5"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
compose = "2.7.0"
roomRuntime = "2.8.2"
roomCompiler = "2.8.2"
roomKtx = "2.8.2"
daggerCompiler = "2.51.1"
roomRuntimeVersion = "2.8.1"
roomCompilerVersion = "2.8.1"
roomKtxVersion = "2.8.1"
lifecycleViewmodelCompose = "2.10.0-alpha05"
lifecycleRuntimeCompose = "2.10.0-alpha05"
comGoogleDaggerHiltAndroidGradlePlugin = "2.56"
hiltAndroid = "2.56"
hiltCompiler = "2.56"
hiltNavigationCompose = "1.3.0"
javapoet = "1.13.0"
hiltAndroidGradlePlugin = "2.57.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose = { group = "com.kizitonwose.calendar", name = "compose", version.ref = "compose" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version = "2.8.2" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version = "2.57.2" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntimeVersion" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompilerVersion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtxVersion" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
com-google-dagger-hilt-android-gradle-plugin = { group = "com.google.dagger.hilt.android", name = "com.google.dagger.hilt.android.gradle.plugin", version.ref = "comGoogleDaggerHiltAndroidGradlePlugin" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version = "2.57.2" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version = "2.57.2" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.3.0" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
hilt-android-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

